### ISSUE TITLE
V1.0 Roadmap

### ISSUE THREAD

**Issue by Darleanow** [Darleanow/WritPins#1]
V1.0 Roadmap 🚀
---

## Styles
- [ ] Enhance title in home page
- [ ] Enhance Navbar styles (icons too big)
- [ ] Space up a bit everything (settings, notifications icon)

## Functionalities

- [ ] Create Pins Data Structure
    - [ ] Implem in mock/pin.ts, must have:
        - [ ] Title
        - [ ] Description, e.g. content
        - [ ] Author
        - [ ] Array of tags
        - [ ] Public/Private 
- [ ] Fetch all public pins and display them on feed
    - [ ] ? Implement smart feed (most viewed filters..)
- [ ] Implement popup to create a pin
- [ ] Implement filter on homepage
- [ ] Popup view for each pin:
    - [ ] Title as Page Titile
    - [ ] Description
    - [ ] Author
    - [ ] Tags
- [ ] List all pins (same functionalities for the feed, but with personal pins), wrap up some code in utils file to avoid duplication.
